// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Brainfuck from "./Brainfuck.res.mjs";

var match = Brainfuck.buildStaticData([]);

var totalSize = match[2];

var sdBf = match[1];

var staticData = match[0];

console.log("Static Data", staticData);

var instruction = [
    sdBf,
    Brainfuck.loadSource(totalSize),
    Brainfuck.push(48, totalSize)
  ].join("\n");

console.log(instruction);

export {
  staticData ,
  sdBf ,
  totalSize ,
  instruction ,
}
/* match Not a pure module */
