// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Brainfuck from "./Brainfuck.res.mjs";

var match = Brainfuck.buildStaticData([
      [
        "var1",
        [21]
      ],
      [
        "myStr",
        Brainfuck.toCharCodes("hello")
      ],
      [
        "name",
        Brainfuck.toCharCodes("Mary!")
      ]
    ]);

var sdBf = match[1];

var instruction = [
    sdBf,
    Brainfuck.mov({
          TAG: "Value",
          _0: 20
        }, 1),
    Brainfuck.mov({
          TAG: "Value",
          _0: 1
        }, 0),
    Brainfuck._and({
          TAG: "Register",
          _0: 1
        })
  ].join("\n");

console.log(instruction);

var staticData = match[0];

var totalSize = match[2];

export {
  staticData ,
  sdBf ,
  totalSize ,
  instruction ,
}
/* match Not a pure module */
