// Generated by ReScript, PLEASE EDIT WITH CARE


var bootstrapper = "\n# BRAINFUCK BOOTSTRAPPER\n->+[\n  >\n  (A) Number of Registries\n  +++\n  Copy initial cell value\n  <[>>+>+<<<-]\n  >>>[<<<+>>>-]<<<\n  Compare if it's (A)\n  >[<->-]<[\n  	Reinit index cell and create next index cell\n  	[-]\n  	>>[>+<<<+>>-]\n    >+<\n  ]\n  >\n]\n>[<<+>>-]>-<<<\n<+[\n  -\n  <<<+\n]-\n";

export {
  bootstrapper ,
}
/* No side effect */
